# Generated by Django 4.2 on 2024-10-04 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^09\\d{9}$')])),
                ('national_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('birthdate', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('issue_place', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'individual_information',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('verify_date', models.DateField(blank=True, null=True)),
                ('unique_identifier', models.BigIntegerField(unique=True)),
                ('individual_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_insurance_policies', to='file.individualinformation')),
            ],
            options={
                'db_table': 'insurance_policy',
            },
        ),
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^09\\d{9}$')])),
                ('issue_place', models.CharField(blank=True, max_length=30, null=True)),
                ('birthdate', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'مجرد'), ('Married', 'متأهل')], default='Single', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')])),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{16}$')])),
                ('dependents', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insured_plan',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=3)),
                ('unique_identifier', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'insurer_info',
                'unique_together': {('name', 'unique_identifier')},
            },
        ),
        migrations.CreateModel(
            name='PolicyHolderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('unique_identifier', models.BigIntegerField(unique=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.insurer')),
            ],
            options={
                'db_table': 'policy_holder_info',
            },
        ),
        migrations.CreateModel(
            name='PlanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('unique_identifier', models.BigIntegerField(unique=True)),
                ('insurance_policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_info', to='file.insurancepolicy')),
            ],
            options={
                'db_table': 'plan_info',
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_insurance_policies', to='file.insurer'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='policy_holder_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_insurance_policied', to='file.policyholderinfo'),
        ),
    ]
