# Generated by Django 4.2 on 2024-10-04 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_individual_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='policyholderinfo',
            unique_together={('name', 'unique_identifier', 'insurer')},
        ),
        migrations.AlterUniqueTogether(
            name='planinfo',
            unique_together={('name', 'unique_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='insurancepolicy',
            unique_together={('number', 'unique_identifier', 'insurer')},
        ),
    ]
