# Generated by Django 4.2 on 2024-09-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planinfo",
            unique_together={("insurance_policy_number", "unique_identifier")},
        ),
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="individual_info",
        ),
        migrations.RemoveField(
            model_name="insurerinfo",
            name="individual_info",
        ),
        migrations.RemoveField(
            model_name="policyholderinfo",
            name="individual_info",
        ),
        migrations.AddField(
            model_name="insurancepolicy",
            name="individual_information",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_insurance_policy",
                to="file.individualinformation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurancepolicy",
            name="insurer_info",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurer_insurance_policy",
                to="file.insurerinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurancepolicy",
            name="plan_info",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_insurance_policy",
                to="file.planinfo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurancepolicy",
            name="policy_holder_info",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holder_insurance_policy",
                to="file.policyholderinfo",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="planinfo",
            name="individual_info",
        ),
    ]
