# Generated by Django 4.2 on 2024-10-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='individual_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insured_person', to='file.individualinformation'),
            preserve_default=False,
        ),
    ]
