# Generated by Django 4.2 on 2024-10-04 08:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='card_number',
            field=models.CharField(default=datetime.datetime(2024, 10, 4, 8, 21, 5, 231422), max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\d{16}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'مجرد'), ('Married', 'متأهل')], default='Single', max_length=10),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')]),
        ),
    ]
