# Generated by Django 4.2 on 2024-10-04 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_insuredperson_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='insurer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_insurance_policies', to='file.insurer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='individual_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_insurance_policies', to='file.individualinformation'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='policy_holder_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holder_insurance_policied', to='file.policyholderinfo'),
        ),
        migrations.AlterField(
            model_name='insuredperson',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{16}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='insurancepolicy',
            unique_together={('number', 'unique_identifier', 'insurer')},
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='insurer_info',
        ),
    ]
