# Generated by Django 4.2 on 2024-10-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_insuredperson_individual_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planinfo',
            name='insurance_policy',
        ),
    ]
