# Generated by Django 4.2 on 2024-10-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_insurancepolicy_insurer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='dependents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='policy_holder_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_insurance_policied', to='file.policyholderinfo'),
        ),
    ]
