# Generated by Django 4.2 on 2024-10-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_remove_planinfo_insurance_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinfo',
            name='insurer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_plan_info', to='file.insurer'),
            preserve_default=False,
        ),
    ]
