# Generated by Django 4.2 on 2024-10-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_insuredperson_dependents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinfo',
            name='insurance_policy',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_info', to='file.insurancepolicy'),
            preserve_default=False,
        ),
    ]
