# Generated by Django 4.2 on 2024-10-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_planinfo_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='plan_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='plan_info_insurance_policy', to='file.planinfo'),
            preserve_default=False,
        ),
    ]
