# Generated by Django 4.2 on 2024-10-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_insurancepolicy_plan_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planinfo',
            unique_together={('name', 'unique_identifier', 'insurer')},
        ),
    ]
