# Generated by Django 4.2 on 2024-10-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_rename_unique_identifier_insurancepolicy_insurance_policy_unique_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='number',
            new_name='insurance_policy_number',
        ),
        migrations.RenameField(
            model_name='insurer',
            old_name='name',
            new_name='insurer_name',
        ),
        migrations.RenameField(
            model_name='planinfo',
            old_name='name',
            new_name='plan_info_name',
        ),
        migrations.RenameField(
            model_name='policyholderinfo',
            old_name='name',
            new_name='policy_holder_name',
        ),
        migrations.AlterUniqueTogether(
            name='insurancepolicy',
            unique_together={('insurance_policy_number', 'insurance_policy_unique_identifier', 'insurer')},
        ),
        migrations.AlterUniqueTogether(
            name='insurer',
            unique_together={('insurer_name', 'insurer_unique_identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='planinfo',
            unique_together={('plan_info_name', 'planinfo_unique_identifier', 'insurer')},
        ),
        migrations.AlterUniqueTogether(
            name='policyholderinfo',
            unique_together={('policy_holder_name', 'policy_holder_unique_identifier', 'insurer')},
        ),
    ]
