# Generated by Django 4.2 on 2024-10-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
