# Generated by Django 4.2 on 2024-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='insurer_unique_identifier',
            field=models.BigIntegerField(),
        ),
    ]
