# Generated by Django 4.2 on 2024-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_alter_insurer_insurer_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyholderinfo',
            name='policy_holder_unique_identifier',
            field=models.BigIntegerField(),
        ),
    ]
