# Generated by Django 4.2 on 2024-10-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_alter_policyholderinfo_policy_holder_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='insurance_policy_unique_identifier',
            field=models.BigIntegerField(),
        ),
    ]
