# Generated by Django 4.2 on 2024-10-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0015_alter_insurancepolicy_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planinfo',
            name='planinfo_unique_identifier',
            field=models.BigIntegerField(),
        ),
    ]
