# Generated by Django 4.2 on 2024-10-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0016_alter_planinfo_planinfo_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredperson',
            name='insurance_policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insured_policy', to='file.insurancepolicy'),
            preserve_default=False,
        ),
    ]
